### ISSUE TITLE
The Delete objects issue - The internal Portal re-indexing script should work in order to depict immediately the new harvesting cycles’ metadata.

### ISSUE THREAD

**Issue by vogias** [teltek/PuMuKIT2-geant-bundle#17]

**Comment by vogias** [comment]
How:
Delete the existing repositories that currently have no metadata.
Add newly added repositories.
Update existing repositories.

**Comment by Alfro** [comment]
The implementation we currently have in mind is to 'Block' repositories and multimedia objects that weren't updated (since they weren't present on the last feed) after the last re-indexing. Later on, there could be a script that deletes really old elements.
This way we ensure we don't delete an element by mistake (E.g: An element skips one harvesting cycle, but is later fixed and added) but at the same time prevents old elements to be shown on the webtv portal.

**Comment by vogias** [comment]
@Alfro i think this is implemented right?

**Comment by Alfro** [comment]
It is. Closing.
