### ISSUE TITLE
The thumbnails for CAMPUSDOMAR videos are all the main logo.

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#40]
Checking on the harvested feed for CAMPUSDOMAR, we realised all thumbnails are the same (main logo of Campus do Mar). Each  object should have its own thumbnail, not a generic one, so we think there could be a problem with the original feed. 
- @vogias Which feed are you using for CAMPUSDOMAR objects?

**Comment by vogias** [comment]
Yes you are right as far as i remember campus do mar repository was down or not accessible for some time(also campus do mar thumbnails) so i transferred the metadata to the geant oai-pmh service and exposed the metadata from there(and added a default thumbnail) in order not to loose it.So if campus do mar is online and available please send me the respective oai-pmh target URL in order to reharvest

**Comment by Alfro** [comment]
@rubenrua Can you take a look at this?

**Comment by Alfro** [comment]
@vogias Right now, the oai-pmh service for campusdomar is down. Could you use the ARCA feeds instead for now? 
All the feeds are listed in this url (it works like with UNED): http://tv.campusdomar.es/arca.xml

**Comment by vogias** [comment]
@Alfro Done. For more details please check : https://services.oer.geant.org/monitoring/#/dashboard/elasticsearch/GEANT%20OER%20Aggregation
 and https://services.oer.geant.org/monitoring/#/dashboard/elasticsearch/GEANT%20OER%20Metadata%20Analysis

**Comment by Alfro** [comment]
@vogias Like on #28, can you use `<media:content url="http://dls.campusdomar.es/pumukitcmar/15/839.mp4" ... >` Instead of the `<link>` block?

**Comment by vogias** [comment]
@Alfro Done

**Comment by Alfro** [comment]
Now the correct thumbnails are viewed in the portal at the staging environment. Closing issue.
